hFigure = figure(...
    'Units','normalized',...
    'Menu','none',...
    'Color','w',...
    'Position', [0.1, 0.1, 0.7, 0.5]);

hAxes = axes(...
    'Parent',hFigure,...
    'Units', 'normalized',...
    'Position', [0.1, 0.1, 0.6, 0.8],...
    'NextPlot','add',... %simular to 'hold on' instruction
    'Box', 'on');

 % 'Callback', 'try, delete(allochild(hAex));end',...
hButton1 = uicontrol(...
    'Style', 'pushbutton',...
    'Callback', 'cla;',...
    'String','Clear',...
    'units','normalized',...
    'Position',[0.8, 0.2, 0.2, 0.15]);

hButton2 = uicontrol(...
    'Style', 'pushbutton',...
    'Callback', 'plot(sin([0:0.01:10]),''r'');',...
    'String','Sin',...
    'units','normalized',...
    'Position',[0.8, 0.4, 0.2, 0.15]);

hButton3 = uicontrol(...
    'Style', 'pushbutton',...
    'Callback', 'plot(cos([0:0.01:10]));',...
    'String','Cos',...
    'units','normalized',...
    'Position',[0.8, 0.6, 0.2, 0.15]);


    